// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/tools/tools.proto

package tools

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	base "section_14/protogen/base"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Software struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoftwareId    uint32                 `protobuf:"varint,1,opt,name=software_id,proto3" json:"software_id,omitempty"`
	Application   *base.Application      `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Software) Reset() {
	*x = Software{}
	mi := &file_proto_tools_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Software) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Software) ProtoMessage() {}

func (x *Software) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tools_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Software.ProtoReflect.Descriptor instead.
func (*Software) Descriptor() ([]byte, []int) {
	return file_proto_tools_tools_proto_rawDescGZIP(), []int{0}
}

func (x *Software) GetSoftwareId() uint32 {
	if x != nil {
		return x.SoftwareId
	}
	return 0
}

func (x *Software) GetApplication() *base.Application {
	if x != nil {
		return x.Application
	}
	return nil
}

var File_proto_tools_tools_proto protoreflect.FileDescriptor

const file_proto_tools_tools_proto_rawDesc = "" +
	"\n" +
	"\x17proto/tools/tools.proto\x1a\x1cproto/base/application.proto\"m\n" +
	"\bSoftware\x12 \n" +
	"\vsoftware_id\x18\x01 \x01(\rR\vsoftware_id\x12?\n" +
	"\vapplication\x18\x02 \x01(\v2\x1d.base.application.ApplicationR\vapplicationB\x1bZ\x19section_14/protogen/toolsb\x06proto3"

var (
	file_proto_tools_tools_proto_rawDescOnce sync.Once
	file_proto_tools_tools_proto_rawDescData []byte
)

func file_proto_tools_tools_proto_rawDescGZIP() []byte {
	file_proto_tools_tools_proto_rawDescOnce.Do(func() {
		file_proto_tools_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tools_tools_proto_rawDesc), len(file_proto_tools_tools_proto_rawDesc)))
	})
	return file_proto_tools_tools_proto_rawDescData
}

var file_proto_tools_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_tools_tools_proto_goTypes = []any{
	(*Software)(nil),         // 0: Software
	(*base.Application)(nil), // 1: base.application.Application
}
var file_proto_tools_tools_proto_depIdxs = []int32{
	1, // 0: Software.application:type_name -> base.application.Application
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tools_tools_proto_init() }
func file_proto_tools_tools_proto_init() {
	if File_proto_tools_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tools_tools_proto_rawDesc), len(file_proto_tools_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tools_tools_proto_goTypes,
		DependencyIndexes: file_proto_tools_tools_proto_depIdxs,
		MessageInfos:      file_proto_tools_tools_proto_msgTypes,
	}.Build()
	File_proto_tools_tools_proto = out.File
	file_proto_tools_tools_proto_goTypes = nil
	file_proto_tools_tools_proto_depIdxs = nil
}
