// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/base/application.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Application struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId       uint32                 `protobuf:"varint,1,opt,name=application_id,proto3" json:"application_id,omitempty"`
	ApplicationFullName string                 `protobuf:"bytes,2,opt,name=application_full_name,proto3" json:"application_full_name,omitempty"`
	Phone               string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email               string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_proto_base_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_proto_base_application_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetApplicationId() uint32 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *Application) GetApplicationFullName() string {
	if x != nil {
		return x.ApplicationFullName
	}
	return ""
}

func (x *Application) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Application) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_base_application_proto protoreflect.FileDescriptor

const file_proto_base_application_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/base/application.proto\x12\x10base.application\"\x97\x01\n" +
	"\vApplication\x12&\n" +
	"\x0eapplication_id\x18\x01 \x01(\rR\x0eapplication_id\x124\n" +
	"\x15application_full_name\x18\x02 \x01(\tR\x15application_full_name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05emailB&Z$microservice_with_grpc/protogen/baseb\x06proto3"

var (
	file_proto_base_application_proto_rawDescOnce sync.Once
	file_proto_base_application_proto_rawDescData []byte
)

func file_proto_base_application_proto_rawDescGZIP() []byte {
	file_proto_base_application_proto_rawDescOnce.Do(func() {
		file_proto_base_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_base_application_proto_rawDesc), len(file_proto_base_application_proto_rawDesc)))
	})
	return file_proto_base_application_proto_rawDescData
}

var file_proto_base_application_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_base_application_proto_goTypes = []any{
	(*Application)(nil), // 0: base.application.Application
}
var file_proto_base_application_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_base_application_proto_init() }
func file_proto_base_application_proto_init() {
	if File_proto_base_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_base_application_proto_rawDesc), len(file_proto_base_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_base_application_proto_goTypes,
		DependencyIndexes: file_proto_base_application_proto_depIdxs,
		MessageInfos:      file_proto_base_application_proto_msgTypes,
	}.Build()
	File_proto_base_application_proto = out.File
	file_proto_base_application_proto_goTypes = nil
	file_proto_base_application_proto_depIdxs = nil
}
